apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-config-nonprd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:moszie248/k8s-calculator-config-nonprd.git
    targetRevision: main
    path: manifest/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: calculator-nonprd-dev
  syncPolicy:
    automated:
      prune: true